/**
 *
 * @author Geppetto Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Geppetto System </br>
 * Geppetto system Copyright - NewPortBay LLC </br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

app = angular.module('Tablet1', ['ionic','ngCordova'])

.config(function($stateProvider, $urlRouterProvider, $httpProvider) {
$httpProvider.defaults.withCredentials = true;
  $stateProvider

  // setup an abstract state for the tabs directive
    .state('app', {
    url: '/app',
    abstract: true,
    templateUrl: 'app/views/menu.html'
  })

  .state('error', {
                url: '/error',
                templateUrl: 'app/views/en/error.html'
            })  

    .state('app.Screen_50-en', {
      url: '/Screen_50-en',
      views: {
        'menuContent': {
          templateUrl: 'app/views/en/Screen_50-en.html',
  controller: 'Tablet1_Default_Activity'
        }
      },
       rolesAllowed: ['ROLE_USER']
    })

  // if none of the above states are matched, use this as the fallback
  $urlRouterProvider.otherwise('/app/Screen_50-en');


})


.controller('MainCtrl', ['$scope','$rootScope', function($scope,$rootScope) {
	$scope.hideSidemenuBackButton = true;
	var top_menu_items;
	top_menu_items = $scope.menu_items = 
[

	{
		is_first_level: true,
		name: "Tablet1_Default_Activity",
		label: "Tablet1_Default_Activity",
		id: 44,
		screens: [
			{
				id: 29,
				is_first_level: false,
				name: "Screen_50-en",
				label: "Screen_50-en",
			}		]	}
];
var getByParentId = function(id) {
	for (var i in top_menu_items) {
		if (top_menu_items[i].id == id) {
			return top_menu_items[i].screens;
		}
	}
}
$scope.showSubcategories = function(category) {
	$scope.menu_items = [];
	var menu_items = getByParentId(category.id);
	$scope.menu_items = angular.copy(menu_items);
	$scope.hideSidemenuBackButton = false;
};
$scope.showTopLevelCategories = function () {
	$scope.menu_items = top_menu_items;
	$scope.hideSidemenuBackButton = true;
};
}])
;