/**
 *
 * @author Schubert Generated Code</br>
 * Date Created: </br>
 * @since  </br>
   build:   </p>
 *
 * code was generated by the Schubert System </br>
 * Schubert system Copyright - NewPortBay LLC copy_right_range</br>
 * The generated code is free to use by anyone</p>
 *
 *
 *
*/

app.controller("Tablet1_Default_Activity", [ '$scope', '$rootScope', '$location', '$window', '$q', '$http', '$ionicPopup', '$timeout', 'RestURL',
				    function( $scope, $rootScope, $location, $window, $q, $http, $ionicPopup, $timeout, RestURL) {

		$scope.Tablet1 = {
		id: '',
		tablet1 : ''
		};





		$scope.init = function(){
		}
		$scope.init();
}]);





